package legacy;

import org.apache.commons.lang3.StringUtils;
import org.json.JSONObject;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;

import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

@RunWith(JUnit4.class)
public class ExampleJournal {
    private final String CONTENT = "{\"nodes\":[{\"Replicate\":{\"name\":\"A\",\n" +
            "  \"ends\":[{\"name\":\"A1\",\n" +
            "    \"type\":\"Source\"},\n" +
            "    {\"name\":\"A2\",\n" +
            "      \"type\":\"Sink\"}]}},\n" +
            "  {\"Replicate\":{\"name\":\"B\",\n" +
            "    \"ends\":[{\"name\":\"B1\",\n" +
            "      \"type\":\"Source\"},\n" +
            "      {\"name\":\"B2\",\n" +
            "        \"type\":\"Sink\"},\n" +
            "      {\"name\":\"B3\",\n" +
            "        \"type\":\"Sink\"}]}},\n" +
            "  {\"Route\":{\"name\":\"C\",\n" +
            "    \"ends\":[{\"name\":\"C1\",\n" +
            "      \"type\":\"Source\"},\n" +
            "      {\"name\":\"C2\",\n" +
            "        \"type\":\"Sink\"},\n" +
            "      {\"name\":\"C3\",\n" +
            "        \"type\":\"Sink\"},\n" +
            "      {\"name\":\"C4\",\n" +
            "        \"type\":\"Sink\"}]}},\n" +
            "  {\"Route\":{\"name\":\"D\",\n" +
            "    \"ends\":[{\"name\":\"D1\",\n" +
            "      \"type\":\"Source\"},\n" +
            "      {\"name\":\"D2\",\n" +
            "        \"type\":\"Sink\"},\n" +
            "      {\"name\":\"D3\",\n" +
            "        \"type\":\"Sink\"},\n" +
            "      {\"name\":\"D4\",\n" +
            "        \"type\":\"Sink\"}]}},\n" +
            "  {\"Route\":{\"name\":\"E\",\n" +
            "    \"ends\":[{\"name\":\"E1\",\n" +
            "      \"type\":\"Source\"},\n" +
            "      {\"name\":\"E2\",\n" +
            "        \"type\":\"Sink\"},\n" +
            "      {\"name\":\"E3\",\n" +
            "        \"type\":\"Sink\"},\n" +
            "      {\"name\":\"E4\",\n" +
            "        \"type\":\"Sink\"}]}},\n" +
            "  {\"Merge\":{\"name\":\"F\",\n" +
            "    \"ends\":[{\"name\":\"F1\",\n" +
            "      \"type\":\"Source\"},\n" +
            "      {\"name\":\"F2\",\n" +
            "        \"type\":\"Source\"},\n" +
            "      {\"name\":\"F3\",\n" +
            "        \"type\":\"Sink\"}]}},\n" +
            "  {\"Replicate\":{\"name\":\"G\",\n" +
            "    \"ends\":[{\"name\":\"G1\",\n" +
            "      \"type\":\"Source\"},\n" +
            "      {\"name\":\"G2\",\n" +
            "        \"type\":\"Sink\"}]}},\n" +
            "  {\"Replicate\":{\"name\":\"H\",\n" +
            "    \"ends\":[{\"name\":\"H1\",\n" +
            "      \"type\":\"Sink\"},\n" +
            "      {\"name\":\"H2\",\n" +
            "        \"type\":\"Source\"}]}},\n" +
            "  {\"Replicate\":{\"name\":\"I\",\n" +
            "    \"ends\":[{\"name\":\"I1\",\n" +
            "      \"type\":\"Source\"},\n" +
            "      {\"name\":\"I2\",\n" +
            "        \"type\":\"Sink\"}]}},\n" +
            "  {\"Replicate\":{\"name\":\"J\",\n" +
            "    \"ends\":[{\"name\":\"J1\",\n" +
            "      \"type\":\"Source\"},\n" +
            "      {\"name\":\"J2\",\n" +
            "        \"type\":\"Sink\"},\n" +
            "      {\"name\":\"J3\",\n" +
            "        \"type\":\"Sink\"},\n" +
            "      {\"name\":\"J4\",\n" +
            "        \"type\":\"Sink\"},\n" +
            "      {\"name\":\"J5\",\n" +
            "        \"type\":\"Sink\"},\n" +
            "      {\"name\":\"J5\",\n" +
            "        \"type\":\"Sink\"}]}},\n" +
            "  {\"Replicate\":{\"name\":\"K\",\n" +
            "    \"ends\":[{\"name\":\"K1\",\n" +
            "      \"type\":\"Source\"},\n" +
            "      {\"name\":\"K2\",\n" +
            "        \"type\":\"Sink\"}]}},\n" +
            "  {\"Replicate\":{\"name\":\"L\",\n" +
            "    \"ends\":[{\"name\":\"L1\",\n" +
            "      \"type\":\"Sink\"},\n" +
            "      {\"name\":\"L2\",\n" +
            "        \"type\":\"Source\"}]}},\n" +
            "  {\"Replicate\":{\"name\":\"M\",\n" +
            "    \"ends\":[{\"name\":\"M1\",\n" +
            "      \"type\":\"Sink\"},\n" +
            "      {\"name\":\"M2\",\n" +
            "        \"type\":\"Source\"}]}},\n" +
            "  {\"Replicate\":{\"name\":\"N\",\n" +
            "    \"ends\":[{\"name\":\"N1\",\n" +
            "      \"type\":\"Source\"},\n" +
            "      {\"name\":\"N2\",\n" +
            "        \"type\":\"Sink\"}]}},\n" +
            "  {\"Replicate\":{\"name\":\"O\",\n" +
            "    \"ends\":[{\"name\":\"O1\",\n" +
            "      \"type\":\"Sink\"},\n" +
            "      {\"name\":\"O2\",\n" +
            "        \"type\":\"Source\"}]}},\n" +
            "  {\"Replicate\":{\"name\":\"P\",\n" +
            "    \"ends\":[{\"name\":\"P1\",\n" +
            "      \"type\":\"Source\"},\n" +
            "      {\"name\":\"P2\",\n" +
            "        \"type\":\"Sink\"}]}},\n" +
            "  {\"Replicate\":{\"name\":\"Q\",\n" +
            "    \"ends\":[{\"name\":\"Q1\",\n" +
            "      \"type\":\"Source\"},\n" +
            "      {\"name\":\"Q2\",\n" +
            "        \"type\":\"Sink\"},\n" +
            "      {\"name\":\"Q3\",\n" +
            "        \"type\":\"Sink\"},\n" +
            "      {\"name\":\"Q4\",\n" +
            "        \"type\":\"Sink\"},\n" +
            "      {\"name\":\"Q5\",\n" +
            "        \"type\":\"Sink\"}]}},\n" +
            "  {\"name\":\"S\",\n" +
            "    \"ends\":[{\"name\":\"S1\",\n" +
            "      \"type\":\"Source\"},\n" +
            "      {\"name\":\"S2\",\n" +
            "        \"type\":\"Sink\"}]},\n" +
            "  {\"name\":\"T\",\n" +
            "    \"ends\":[{\"name\":\"T1\",\n" +
            "      \"type\":\"Source\"},\n" +
            "      {\"name\":\"T2\",\n" +
            "        \"type\":\"Sink\"}]},\n" +
            "  {\"name\":\"U\",\n" +
            "    \"ends\":[{\"name\":\"U1\",\n" +
            "      \"type\":\"Sink\"},\n" +
            "      {\"name\":\"U2\",\n" +
            "        \"type\":\"Source\"}]}],\n" +
            "  \"readers\":[{\"name\":\"R1\",\n" +
            "    \"ends\":[{\"name\":\"R12\",\n" +
            "      \"type\":\"Sink\"}]},\n" +
            "    {\"name\":\"R2\",\n" +
            "      \"ends\":[{\"name\":\"R22\",\n" +
            "        \"type\":\"Sink\"}]},\n" +
            "    {\"name\":\"R3\",\n" +
            "      \"ends\":[{\"name\":\"R32\",\n" +
            "        \"type\":\"Sink\"}]},\n" +
            "    {\"name\":\"R4\",\n" +
            "      \"ends\":[{\"name\":\"R42\",\n" +
            "        \"type\":\"Sink\"}]}],\n" +
            "  \"writers\":[{\"name\":\"W1\",\n" +
            "    \"ends\":[{\"name\":\"W11\",\n" +
            "      \"type\":\"Source\"}]},\n" +
            "    {\"name\":\"W2\",\n" +
            "      \"ends\":[{\"name\":\"W21\",\n" +
            "        \"type\":\"Source\"}]},\n" +
            "    {\"name\":\"W3\",\n" +
            "      \"ends\":[{\"name\":\"W31\",\n" +
            "        \"type\":\"Source\"}]}],\n" +
            "  \"channels\":[{\"Sync\":[{\"Source\":\"A2B\"},\n" +
            "    {\"Sink\":\"AB1\"}]},\n" +
            "    {\"FIFO\":[{\"Source\":\"B2C\"},\n" +
            "      {\"Sink\":\"BC1\"}]},\n" +
            "    {\"FIFO\":[{\"Source\":\"C2D\"},\n" +
            "      {\"Sink\":\"CD1\"}]},\n" +
            "    {\"Sync\":[{\"Source\":\"D2F\"},\n" +
            "      {\"Sink\":\"DF1\"}]},\n" +
            "    {\"FIFO\":[{\"Source\":\"F3G\"},\n" +
            "      {\"Sink\":\"FG1\"}]},\n" +
            "    {\"FIFO\":[{\"Source\":\"B3E\"},\n" +
            "      {\"Sink\":\"BE1\"}]},\n" +
            "    {\"Sync\":[{\"Source\":\"E2F\"},\n" +
            "      {\"Sink\":\"EF2\"}]},\n" +
            "    {\"SyncDrain\":[{\"Source\":\"E4T\"},\n" +
            "      {\"Source\":\"ET2\"}]},\n" +
            "    {\"Sync\":[{\"Source\":\"Q2T\"},\n" +
            "      {\"Sink\":\"QT1\"}]},\n" +
            "    {\"PrioritySync2\":[{\"Source\":\"S2Q\"},\n" +
            "      {\"Sink\":\"SQ1\"}]},\n" +
            "    {\"FIFO\":[{\"Source\":\"Q5P\"},\n" +
            "      {\"Sink\":\"QP1\"}]},\n" +
            "    {\"Lossy\":[{\"Source\":\"Q3O\"},\n" +
            "      {\"Sink\":\"QO2\"}]},\n" +
            "    {\"Lossy\":[{\"Source\":\"Q4H\"},\n" +
            "      {\"Sink\":\"QH2\"}]},\n" +
            "    {\"SyncDrain\":[{\"Source\":\"O1D\"},\n" +
            "      {\"Source\":\"OD4\"}]},\n" +
            "    {\"SyncDrain\":[{\"Source\":\"H1C\"},\n" +
            "      {\"Source\":\"HC4\"}]},\n" +
            "    {\"SyncDrain\":[{\"Source\":\"C3M\"},\n" +
            "      {\"Source\":\"CM1\"}]},\n" +
            "    {\"SyncDrain\":[{\"Source\":\"D3U\"},\n" +
            "      {\"Source\":\"DU1\"}]},\n" +
            "    {\"Lossy\":[{\"Source\":\"J3M\"},\n" +
            "      {\"Sink\":\"JM2\"}]},\n" +
            "    {\"Lossy\":[{\"Source\":\"J6U\"},\n" +
            "      {\"Sink\":\"JU2\"}]},\n" +
            "    {\"PrioritySync1\":[{\"Source\":\"I2J\"},\n" +
            "      {\"Sink\":\"IJ1\"}]},\n" +
            "    {\"FIFO\":[{\"Source\":\"J2K\"},\n" +
            "      {\"Sink\":\"JK1\"}]},\n" +
            "    {\"Sync\":[{\"Source\":\"J4L\"},\n" +
            "      {\"Sink\":\"JL2\"}]},\n" +
            "    {\"FIFO\":[{\"Source\":\"J5N\"},\n" +
            "      {\"Sink\":\"JN1\"}]},\n" +
            "    {\"SyncDrain\":[{\"Source\":\"E3L\"},\n" +
            "      {\"Source\":\"EL1\"}]}],\n" +
            "  \"connections\":[{\"one\":\"W11\",\n" +
            "    \"two\":\"I1\"},\n" +
            "    {\"one\":\"I2\",\n" +
            "      \"two\":\"I2J\"},\n" +
            "    {\"one\":\"W21\",\n" +
            "      \"two\":\"A1\"},\n" +
            "    {\"one\":\"A2B\",\n" +
            "      \"two\":\"A2\"},\n" +
            "    {\"one\":\"AB1\",\n" +
            "      \"two\":\"B1\"},\n" +
            "    {\"one\":\"B2C\",\n" +
            "      \"two\":\"B2\"},\n" +
            "    {\"one\":\"B3E\",\n" +
            "      \"two\":\"B3\"},\n" +
            "    {\"one\":\"BC1\",\n" +
            "      \"two\":\"C1\"},\n" +
            "    {\"one\":\"C2D\",\n" +
            "      \"two\":\"C2\"},\n" +
            "    {\"one\":\"E3L\",\n" +
            "      \"two\":\"C3\"},\n" +
            "    {\"one\":\"A2B\",\n" +
            "      \"two\":\"HC4\"},\n" +
            "    {\"one\":\"CD1\",\n" +
            "      \"two\":\"D1\"},\n" +
            "    {\"one\":\"D2F\",\n" +
            "      \"two\":\"D2\"},\n" +
            "    {\"one\":\"D3U\",\n" +
            "      \"two\":\"D3\"},\n" +
            "    {\"one\":\"OD4\",\n" +
            "      \"two\":\"D4\"},\n" +
            "    {\"one\":\"BE1\",\n" +
            "      \"two\":\"E1\"},\n" +
            "    {\"one\":\"E2F\",\n" +
            "      \"two\":\"E2\"},\n" +
            "    {\"one\":\"E3L\",\n" +
            "      \"two\":\"E3\"},\n" +
            "    {\"one\":\"E4T\",\n" +
            "      \"two\":\"E4\"},\n" +
            "    {\"one\":\"DF1\",\n" +
            "      \"two\":\"F1\"},\n" +
            "    {\"one\":\"EF2\",\n" +
            "      \"two\":\"F2\"},\n" +
            "    {\"one\":\"F3G\",\n" +
            "      \"two\":\"F3\"},\n" +
            "    {\"one\":\"FG1\",\n" +
            "      \"two\":\"G1\"},\n" +
            "    {\"one\":\"R32\",\n" +
            "      \"two\":\"G2\"},\n" +
            "    {\"one\":\"H1C\",\n" +
            "      \"two\":\"H1\"},\n" +
            "    {\"one\":\"QH2\",\n" +
            "      \"two\":\"H2\"},\n" +
            "    {\"one\":\"A2B\",\n" +
            "      \"two\":\"A2\"},\n" +
            "    {\"one\":\"J2K\",\n" +
            "      \"two\":\"J2\"},\n" +
            "    {\"one\":\"J3M\",\n" +
            "      \"two\":\"J3\"},\n" +
            "    {\"one\":\"J4L\",\n" +
            "      \"two\":\"J4\"},\n" +
            "    {\"one\":\"J5N\",\n" +
            "      \"two\":\"J5\"},\n" +
            "    {\"one\":\"J6U\",\n" +
            "      \"two\":\"J6\"},\n" +
            "    {\"one\":\"JK1\",\n" +
            "      \"two\":\"K1\"},\n" +
            "    {\"one\":\"R12\",\n" +
            "      \"two\":\"K2\"},\n" +
            "    {\"one\":\"CM1\",\n" +
            "      \"two\":\"M1\"},\n" +
            "    {\"one\":\"JM2\",\n" +
            "      \"two\":\"M2\"},\n" +
            "    {\"one\":\"JN1\",\n" +
            "      \"two\":\"N1\"},\n" +
            "    {\"one\":\"R22\",\n" +
            "      \"two\":\"N2\"},\n" +
            "    {\"one\":\"O1D\",\n" +
            "      \"two\":\"O1\"},\n" +
            "    {\"one\":\"QO2\",\n" +
            "      \"two\":\"O2\"},\n" +
            "    {\"one\":\"A2B\",\n" +
            "      \"two\":\"A2\"},\n" +
            "    {\"one\":\"QP1\",\n" +
            "      \"two\":\"P1\"},\n" +
            "    {\"one\":\"R42\",\n" +
            "      \"two\":\"P2\"},\n" +
            "    {\"one\":\"W31\",\n" +
            "      \"two\":\"S1\"},\n" +
            "    {\"one\":\"S2Q\",\n" +
            "      \"two\":\"S2\"},\n" +
            "    {\"one\":\"QT1\",\n" +
            "      \"two\":\"T1\"},\n" +
            "    {\"one\":\"ET2\",\n" +
            "      \"two\":\"T2\"},\n" +
            "    {\"one\":\"DU1\",\n" +
            "      \"two\":\"U1\"},\n" +
            "    {\"one\":\"JU2\",\n" +
            "      \"two\":\"U2\"}\n" +
            "    ]}";
    @Test
    public void example() {
        final JSONObject jsonObject = new JSONObject(CONTENT);
        assertEquals(20, jsonObject.getJSONArray("nodes").length());
        assertEquals(49, jsonObject.getJSONArray("connections").length());
        assertEquals(24, jsonObject.getJSONArray("channels").length());
        assertEquals(4, jsonObject.getJSONArray("readers").length());
        assertEquals(3, jsonObject.getJSONArray("writers").length());

    }
}
